[package]
name = "luminary"
version.workspace = true
edition.workspace = true
repository = "https://github.com/FreeMasen/luminary"
authors = ["Robert Masen <r.f.masen@gmail.com>"]
description = "A compiler for lua."

[dependencies]
analisar = "0.2"
clap = { version = "4.4", features = ["derive"] }
inkwell = { version = "0.2", features = ["llvm16-0"] }
lex_lua = "0.1.9"
runtime = { package = "luminary-runtime", path = "crates/runtime-lib", features = [
    "names",
] }
tempfile = "3.8"

[dev-dependencies]
insta = "1.31"
proptest = "1.2"
serde_json = "1"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0-pre1"
edition = "2021"
publish = true

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.8.0"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "upload"
# Whether +crt-static should be used on msvc
msvc-crt-static = false
# Whether CI should include auto-generated code to build local artifacts
build-local-artifacts = false
# Local artifacts jobs to run in CI
local-artifacts-jobs = ["./local-build-binary"]
precise-builds = true

# [[workspace.metadata.dist.extra-artifacts]]
# artifacts = ["target/release/libluminary_runtime.*"]
# build = [
#     "cargo",
#     "rustc",
#     "--release",
#     "--features",
#     "runtime",
#     "-p",
#     "luminary-runtime",
#     "--crate-type",
#     "cdylib,staticlib",
# ]
