[package]
name = "luminary"
version.workspace = true
edition.workspace = true
repository = "https://github.com/FreeMasen/luminary"
homepage = "https://gh.freemasen.com/luminary"
authors = ["Robert Masen <r.f.masen@gmail.com>"]
description = "A compiler for lua."

[dependencies]
clap = { version = "4.4", features = ["derive"] }
cfg-if = "1.0.0"
dunce = "1.0"
env_logger = "0.11"
inkwell = { version = "0.5", features = ["llvm18-0"] }
log.workspace = true
tempfile = "3.8"
rand = "0.8"
codegen = { path = "crates/luminary-codegen", package = "luminary-codegen" }

[workspace.dependencies]
analisar = "0.4"
bstr = "1.9"
lex_lua = "0.2.0"
log = "0.4"


[features]

[dev-dependencies]
escargot = "0.5"
insta = "1.31"
mlua = { version = "0.9", features = ["lua53", "vendored"] }
proptest = "1.2"
serde_json = "1"
uuid = { version = "1.10", features = ["v4"] }
criterion = "0.3"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0-junk1"
edition = "2021"
publish = true
