[package]
name = "luminary"
version.workspace = true
edition.workspace = true
repository = "https://github.com/FreeMasen/luminary"
homepage = "https://gh.freemasen.com/luminary"
authors = ["Robert Masen <r.f.masen@gmail.com>"]
description = "A compiler for lua."

[dependencies]
analisar = "0.4"
bstr = "1.9"
clap = { version = "4.4", features = ["derive"] }
env_logger = "0.11"
inkwell = { version = "0.4", features = ["llvm16-0"], optional = true }
lex_lua = "0.2.0"
runtime = { package = "luminary-runtime", path = "crates/runtime-lib", features = [
    "names",
] }
tempfile = "3.8"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
log = "0.4"

[features]
default = ["codegen"]
codegen = ["dep:inkwell"]



[dev-dependencies]
escargot = "0.5"
insta = "1.31"
mlua = { version = "0.9", features = ["lua53", "vendored"] }
proptest = "1.2"
serde_json = "1"
uuid = { version = "1.10", features = ["v4"] }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[workspace]
members = ["crates/*"]

[workspace.package]
version = "0.1.0-junk1"
edition = "2021"
publish = true

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.20.0-prerelease.3"
# CI backends to support
ci = ["github"]
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
tap = "FreeMasen/homebrew-tap"
publish-jobs = ["homebrew"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
]
# Publish jobs to run in CI
pr-run-mode = "upload"
# Whether +crt-static should be used on msvc
msvc-crt-static = false
# Local artifacts jobs to run in CI
github-build-setup = "misc/build-setup.yml"
# Build only the required packages, and individually
precise-builds = true

[workspace.metadata.dist.github-custom-runners]
aarch64-apple-darwin = "macos-13"
