[package]
name = "luminary"
version = "0.1.0"
edition = "2021"

[dependencies]
analisar = "0.2"
clap = { version = "4.4", features = [ "derive" ] }
inkwell = { version = "0.2", features = ["llvm16-0"] }
lex_lua = "0.1.9"
tempfile = "3.8"

[dev-dependencies]
insta = "1.31"
proptest = "1.2"
