- name: Install LLVM and Clang
  id: install
  uses: FreeMasen/llvm-install-action@v1.0.5
  if: ${{ !startsWith(matrix.os, 'windows') }}
  with:
    version: 18.1.8
- name: Install LLVM and Clang
  id: install
  uses: FreeMasen/llvm-install-action@v1.0.5
  if: ${{ startsWith(matrix.os, 'windows') }}
  with:
    version: 18.1.7
    
