#! /bin/bash

echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
echo "PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR" >> $GITHUB_ENV
echo "CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH" >> $GITHUB_ENV
echo "CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH" >> $GITHUB_ENV
source $HOME/.cargo/env
echo "PATH=$PATH" >> $GITHUB_ENV
