name: Build Runtime
permissions:
  contents: write
on:
  release:
    types: 
      - published
  push:
    branches:
      - rust-std

  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:

  build-runtime:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - windows-2019
          - windows-2022
          - macos-11
          - macos-12
    runs-on: ${{ matrix.os }}
    env:
      TARGET_DIR: ${{ github.workspace }}/luminary_runtime-${{ matrix.os }}-${{github.ref_name}}
      COMP_SUFFIX: ${{ startsWith(matrix.os, 'windows') && '7z' || 'tar.gz' }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - name: build runtime libs
      id: build-runtime
      run: >-
        cargo clean &&
        cargo build --release -p luminary-runtime --features runtime --lib
    - name: find files Windows
      if: runner.os == 'Windows'
      shell: bash
      run: >-
        mkdir $TARGET_DIR
        && ls . && ls ./target/release
        && cp ./target/release/luminary_runtime.lib $TARGET_DIR/luminary_runtime.lib
        && cp ./target/release/luminary_runtime.dll $TARGET_DIR/luminary_runtime.dll
        && cd $TARGET_DIR
        && 7z a -mx9 "$TARGET_DIR.$COMP_SUFFIX" .
    - name: find files Macos
      if: runner.os == 'Macos'
      shell: bash
      run: >-
        mkdir -p $TARGET_DIR
        && ls . && ls ./target/release
        && cp ./target/release/libluminary_runtime.a $TARGET_DIR/libluminary_runtime.a
        && cp ./target/release/libluminary_runtime.dylib $TARGET_DIR/libluminary_runtime.dylib
        && cd $TARGET_DIR
        && tar --strip-components=1 -czf $TARGET_DIR.$COMP_SUFFIX .
    - name: find files Linux
      if: runner.os == 'Linux'
      shell: bash
      run: >-
        mkdir -p $TARGET_DIR
        && cp ./target/release/libluminary_runtime.a $TARGET_DIR/libluminary_runtime.a
        && cp ./target/release/libluminary_runtime.so $TARGET_DIR/libluminary_runtime.so
        && cd $TARGET_DIR
        && tar --strip-components=1 -czf $TARGET_DIR.$COMP_SUFFIX .
    - name: Upload
      uses: actions/upload-artifact@v4
      if: github.event.pull_request
      with:
        name: luminary_libs-${{ matrix.os }}-${{ github.ref_name }}
        path: ${{ env.TARGET_DIR }}.${{ env.COMP_SUFFIX }}
        overwrite: true
    - name: Upload Release
      if: ${{ !github.event.pull_request }}
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ env.TARGET_DIR }}.${{ env.COMP_SUFFIX }}
