name: Build Runtime

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu-static:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build runtime staticlib
      id: build-runtime-static
      run: >-
        cargo clean &&
        cargo rustc --release -p luminary-runtime
        --features runtime --crate-type staticlib --lib
    - name: "Upload artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: staticlib
        path: ./target/release/libluminary_runtime.a
  build-ubuntu-dyn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build runtime cdylib
      id: build-runtime-dyn
      run: >-
        cargo clean &&
        cargo rustc --release -p luminary-runtime
        --features runtime --crate-type cdylib --lib
    - name: "Upload artifacts"
      uses: actions/upload-artifact@v3
      with:
        name: staticlib
        path: ./target/release/libluminary_runtime.so
