name: Rust

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

env:
  CARGO_TERM_COLOR: always
  # PKG_CONFIG_PATH: '/opt/homebrew/opt/zstd/lib/pkgconfig:/opt/homebrew/opt/lz4/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig'
  # PKG_CONFIG_LIBDIR: '/usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/14'
  # OBJC: clang
  # CC: clang
  # OBJCXX: clang++
  # CXX: clang++
jobs:
  test_runtime:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test-runtime
      env: 
        LUMINARY_PRINT_TVALUE: 1
  integration_tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-14
          - windows-latest
      fail-fast: false
    runs-on: ${{matrix.os}}
    env:
      LUMINARY_USE_VERBOSE_CLANG: 1
    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang (Linux)
      id: install
      uses: FreeMasen/llvm-install-action@v1.0.4
      with:
        version: 16.0.6
        set-path: 'false'
    - name: Run Link Integration Tests
      run: cargo test-codegen --test link
    - name: Run Math Integration Tests
      run: cargo test-codegen --test math
    - name: Run Basic Functions Integration Tests
      run: cargo test-codegen --test basic_fns
    - name: Run Basic Functions Integration Tests
      run: cargo test-codegen --test logic
