name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.8.3
      with:
        # The version of LLVM and Clang binaries to install.
        version: 16
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: >- 
        cargo test --lib --verbose &&
        cargo test -p luminary-runtime --features runtime
      env: 
        LLVM_SYS_160_PREFIX: ${{ env.LLVM_PATH }}
        LUMINARY_PRINT_TVALUE: 1
  integration_tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang (Linux)
      if: runner.os == 'Linux'
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
        force-version: true
        ubuntu-version: 20.04
        version: 16.0.6
        directory: ${{ github.workspace }}/llvm
    - name: Install LLVM and Clang (Windows)
      if: runner.os == 'Windows'
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
        force-version: true
        directory: C:\LLVM
        version: 16.0.6
    - name: Install LLVM and Clang (MacOS)
      if: runner.os == 'Macos' && matrix.targets[0] != 'aarch64-apple-darwin'
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
        force-version: true
        version: 16.0.6
        directory: ${{ github.workspace }}/llvm
    - name: Install LLVM and Clang (MacOS-AArch64)
      if: runner.os == 'Macos' && matrix.targets[0] == 'aarch64-apple-darwin'
      uses: FreeMasen/install-llvm-action@c9be196bafb9b4f4a7486019d3e525be0b4dc110
      with:
        download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
        force-version: true
        version: 16.0.6
        arch: aarch64
        directory: ${{ github.workspace }}/llvm
    - name: update llvm-sys env var (MacOS)
      if: runner.os == 'Macos'
      run: echo "LLVM_SYS_160_PREFIX=$($GITHUB_WORKSPACE/llvm/bin/llvm-config --prefix)" >> "$GITHUB_ENV"
    - name: update llvm-sys env var (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install build-essential
        echo "LLVM_SYS_160_PREFIX=$($GITHUB_WORKSPACE/llvm/bin/llvm-config --prefix)" >> "$GITHUB_ENV"
    - name: update llvm-sys env var (Windows)
      if: runner.os == 'Windows'
      run:  |
        $var = C:\LLVM\bin\llvm-config --prefix
        echo "LLVM_SYS_160_PREFIX=$var" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    - name: Run Math Integration Tests
      run: cargo test --test math
