# Copyright 2022-2023, axodotdev
# SPDX-License-Identifier: MIT or Apache-2.0
#
# CI that:
#
# * checks for a Git Tag that looks like a release
# * builds artifacts with cargo-dist (archives, installers, hashes)
# * uploads those artifacts to temporary workflow zip
# * on success, uploads the artifacts to a Github Release™
#
# Note that the Github Release™ will be created with a generated
# title/body based on your changelogs.
name: Build-Release-Windows
on:
  # push:
  #   tags:
  #     - '**[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        download-url: https://github.com/FreeMasen/llvm-builds/releases/download/v16.0.6
        force-version: true
        directory: C:\LLVM
        version: 16.0.6
    - name: Build
      run: cargo build --release
      env:
        LLVM_SYS_160_PREFIX: 'C:\LLVM'
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: target/release/luminary.exe
